sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t levonsargsyan1990/docker-react .

script:
    - docker run levonsargsyan1990/docker-react npm run test -- --coverage